//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ezzylearning.com/services/CountryInformationService.asmx", ConfigurationName="CountryInformationServiceSoap")]
public interface CountryInformationServiceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetServiceNam" +
        "e", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetServiceName();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetServiceNam" +
        "e", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetServiceNameAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountries", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetCountries();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountries", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> GetCountriesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
        "woLetterISOCode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCountryByTwoLetterISOCode(string twoLetterISOCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
        "woLetterISOCode", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCountryByTwoLetterISOCodeAsync(string twoLetterISOCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetTwoLetterI" +
        "SOCodeByCountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetTwoLetterISOCodeByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetTwoLetterI" +
        "SOCodeByCountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetTwoLetterISOCodeByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
        "hreeLetterISOCode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCountryByThreeLetterISOCode(string threeLetterISOCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByT" +
        "hreeLetterISOCode", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCountryByThreeLetterISOCodeAsync(string threeLetterISOCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetThreeLette" +
        "rISOCodeByCountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetThreeLetterISOCodeByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetThreeLette" +
        "rISOCodeByCountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetThreeLetterISOCodeByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCapitalByC" +
        "ountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCapitalByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCapitalByC" +
        "ountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCapitalByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetAreaInKMBy" +
        "Country", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetAreaInKMByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetAreaInKMBy" +
        "Country", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetAreaInKMByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetPopulation" +
        "ByCountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetPopulationByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetPopulation" +
        "ByCountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetPopulationByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetContinents" +
        "", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetContinents();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetContinents" +
        "", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> GetContinentsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountriesB" +
        "yContinent", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetCountriesByContinent(string continentCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountriesB" +
        "yContinent", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> GetCountriesByContinentAsync(string continentCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByC" +
        "urrencyCode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCountryByCurrencyCode(string currencyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCountryByC" +
        "urrencyCode", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCountryByCurrencyCodeAsync(string currencyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencies" +
        "", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetCurrencies();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencies" +
        "", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Data.DataSet> GetCurrenciesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyCo" +
        "deByCountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCurrencyCodeByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyCo" +
        "deByCountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCurrencyCodeByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyNa" +
        "meByCountry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCurrencyNameByCountry(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyNa" +
        "meByCountry", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCurrencyNameByCountryAsync(string countryName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyBy" +
        "CurrencyCode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetCurrencyByCurrencyCode(string currencyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.ezzylearning.com/services/CountryInformationService.asmx/GetCurrencyBy" +
        "CurrencyCode", ReplyAction="*")]
    System.Threading.Tasks.Task<string> GetCurrencyByCurrencyCodeAsync(string currencyCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CountryInformationServiceSoapChannel : CountryInformationServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CountryInformationServiceSoapClient : System.ServiceModel.ClientBase<CountryInformationServiceSoap>, CountryInformationServiceSoap
{
    
    public CountryInformationServiceSoapClient()
    {
    }
    
    public CountryInformationServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CountryInformationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryInformationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryInformationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetServiceName()
    {
        return base.Channel.GetServiceName();
    }
    
    public System.Threading.Tasks.Task<string> GetServiceNameAsync()
    {
        return base.Channel.GetServiceNameAsync();
    }
    
    public System.Data.DataSet GetCountries()
    {
        return base.Channel.GetCountries();
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> GetCountriesAsync()
    {
        return base.Channel.GetCountriesAsync();
    }
    
    public string GetCountryByTwoLetterISOCode(string twoLetterISOCode)
    {
        return base.Channel.GetCountryByTwoLetterISOCode(twoLetterISOCode);
    }
    
    public System.Threading.Tasks.Task<string> GetCountryByTwoLetterISOCodeAsync(string twoLetterISOCode)
    {
        return base.Channel.GetCountryByTwoLetterISOCodeAsync(twoLetterISOCode);
    }
    
    public string GetTwoLetterISOCodeByCountry(string countryName)
    {
        return base.Channel.GetTwoLetterISOCodeByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetTwoLetterISOCodeByCountryAsync(string countryName)
    {
        return base.Channel.GetTwoLetterISOCodeByCountryAsync(countryName);
    }
    
    public string GetCountryByThreeLetterISOCode(string threeLetterISOCode)
    {
        return base.Channel.GetCountryByThreeLetterISOCode(threeLetterISOCode);
    }
    
    public System.Threading.Tasks.Task<string> GetCountryByThreeLetterISOCodeAsync(string threeLetterISOCode)
    {
        return base.Channel.GetCountryByThreeLetterISOCodeAsync(threeLetterISOCode);
    }
    
    public string GetThreeLetterISOCodeByCountry(string countryName)
    {
        return base.Channel.GetThreeLetterISOCodeByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetThreeLetterISOCodeByCountryAsync(string countryName)
    {
        return base.Channel.GetThreeLetterISOCodeByCountryAsync(countryName);
    }
    
    public string GetCapitalByCountry(string countryName)
    {
        return base.Channel.GetCapitalByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetCapitalByCountryAsync(string countryName)
    {
        return base.Channel.GetCapitalByCountryAsync(countryName);
    }
    
    public string GetAreaInKMByCountry(string countryName)
    {
        return base.Channel.GetAreaInKMByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetAreaInKMByCountryAsync(string countryName)
    {
        return base.Channel.GetAreaInKMByCountryAsync(countryName);
    }
    
    public string GetPopulationByCountry(string countryName)
    {
        return base.Channel.GetPopulationByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetPopulationByCountryAsync(string countryName)
    {
        return base.Channel.GetPopulationByCountryAsync(countryName);
    }
    
    public System.Data.DataSet GetContinents()
    {
        return base.Channel.GetContinents();
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> GetContinentsAsync()
    {
        return base.Channel.GetContinentsAsync();
    }
    
    public System.Data.DataSet GetCountriesByContinent(string continentCode)
    {
        return base.Channel.GetCountriesByContinent(continentCode);
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> GetCountriesByContinentAsync(string continentCode)
    {
        return base.Channel.GetCountriesByContinentAsync(continentCode);
    }
    
    public string GetCountryByCurrencyCode(string currencyCode)
    {
        return base.Channel.GetCountryByCurrencyCode(currencyCode);
    }
    
    public System.Threading.Tasks.Task<string> GetCountryByCurrencyCodeAsync(string currencyCode)
    {
        return base.Channel.GetCountryByCurrencyCodeAsync(currencyCode);
    }
    
    public System.Data.DataSet GetCurrencies()
    {
        return base.Channel.GetCurrencies();
    }
    
    public System.Threading.Tasks.Task<System.Data.DataSet> GetCurrenciesAsync()
    {
        return base.Channel.GetCurrenciesAsync();
    }
    
    public string GetCurrencyCodeByCountry(string countryName)
    {
        return base.Channel.GetCurrencyCodeByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetCurrencyCodeByCountryAsync(string countryName)
    {
        return base.Channel.GetCurrencyCodeByCountryAsync(countryName);
    }
    
    public string GetCurrencyNameByCountry(string countryName)
    {
        return base.Channel.GetCurrencyNameByCountry(countryName);
    }
    
    public System.Threading.Tasks.Task<string> GetCurrencyNameByCountryAsync(string countryName)
    {
        return base.Channel.GetCurrencyNameByCountryAsync(countryName);
    }
    
    public string GetCurrencyByCurrencyCode(string currencyCode)
    {
        return base.Channel.GetCurrencyByCurrencyCode(currencyCode);
    }
    
    public System.Threading.Tasks.Task<string> GetCurrencyByCurrencyCodeAsync(string currencyCode)
    {
        return base.Channel.GetCurrencyByCurrencyCodeAsync(currencyCode);
    }
}
